default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 

cache_default: &cache_default
  adapter: postgresql
  encoding: unicode
  migration_path: db/migrate/cache
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
  timeout: 5000

development:
  primary:
    <<: *default
    database: score_saga_development
  cache:
    <<: *cache_default
    database: score_saga_development_cache

test:
  <<: *default
  database: score_saga_test

production:
  <<: *default
  database: score_saga_production
  username: score_saga
  password: <%= ENV["SCORE_SAGA_DATABASE_PASSWORD"] %>
