default:
  store_options: &default_store_options
  max_age: <%= 60.days.to_i %>
  namespace: <%= Rails.env %>
  max_size: <%= 1.gigabyte %>
  size_estimate_samples: 1000

development: &development
  database: cache
  store_options:
    <<: *default_store_options

production: &production
  database: cache
  store_options:
    <<: *default_store_options